---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids: ['ci-testing']
  instance_type: c3.large
  interface: public

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      image_id: ami-190e4b73
      tags:
        Name: travis-ci-default-ubuntu-1204
        Env: public

suites:
  - name: default
    run_list: recipe[et_fog]
