language: ruby
rvm:
- 2.2
sudo: false
cache:
  directories:
  - vendor/bundle
  - "~/.berkshelf"
before_install:
- echo -n $EC2_KEY_CHUNK_{0..30} >> ~/.ssh/travis_ci_ec2.base64
- cat ~/.ssh/travis_ci_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/travis_ci_ec2.pem
- mkdir ~/.chef
- touch ~/.chef/knife.rb
- chmod 600 ~/.chef/knife.rb ~/.ssh/travis_ci_ec2.pem
install:
- bundle install --without local --deployment --jobs=3 --retry=3
- bundle exec berks install
script:
- bundle exec rake travis
notifications:
  slack:
    secure: NOfZLlBbYzXoGw6d4GIMdn/rkBfaVZo+gTNDmRTNLvysjEJrO0q9E95VFZnruM5S8bhacCfmKjy1zuraePqrrOg6qhBN22MzkIxk3yZx6SXIyQ/y0vJuqlFt8JF8Yd7xS8SZIsGuGJot4BCykZXbMfXDTb6g4DkOkWOWIsV0B0c=
env:
  global:
  - secure: bVz2fe6RdTkce4E/P5fwkntgkdMVeBlE2iCpSXf1/NFz6mzHRJq14z/kzZz124N6+JrY/1/1NwoZtoEaKnr+FUBdnBZ+zcYdwo+hHGUYjLJKD6zaPl8x/davvU7nHlxdUQCb2gZF9ZjVEN/FOpz93IpM4T1uaJTs8VEsPkFWOqI=
  - secure: dqpPzvvbq4pWqf9x8fwddnf0LuVHUPoOV7X4J245TpPX0IgqoEZt9nqO0+QpQFjXiFKyVMWcVHt2ExvJ+U6rTOdTfS3/5r7sPLX8C+FSYgcAFedA/GmoBV9YZf3dTvxaAvxHD6MdjGAwqAp7hHAtkHJJuzxzLmwqWCyi9ujOC6Y=
  - secure: GWa8e/ICPCEFUEwRSBtwGljbT8cpGLBlDgKXVf7FaZj8ZZXF7vG4yLapKpmvdLkRKurH054cqz26FNvDwQVwcdqb0MhrxH2+5Mavrp0HxukjbEWTYEA0VP52KjEJewQDafTPo0IxujtovFobvWUD+1bFMDvtigCbpaX7qm1BzTU=
  - secure: Cd8iLDHzhijIyxvk9nXcduihKx4WzxSeb+bghrroAwOfLGrRI1q9lwT9psKiFCQI9N723pnVZEzCEae6zw6exNj4tX0UHj4dOauBffIcvFS0zpOEVIbaBpNHDH7DbLQtER5hF6mWtLKkYIFjl5htn0etBA9JZom7lbKjsOyHb94=
  - secure: j9FD7L7uE+ghLJsKRja7huzRMxZNB8I7rOMelYmNJ/BiRUdPrANUJcAUe7q9U+04qptDXXUrRG+RVXjOnZEpkqxzH2cEN/dRLVNY95ZcLdkyK6Dxfj8ofVIxzogun5dt2/8HaWh/5wsFuLDGlbhvpN1JXKBmNKi22qMAxgmUcCQ=
  - secure: Ei+lxlNQ1Veh6+7WWZs0L2bA/q36jtTG8jedUWRMQmq6+B+ccRyEO2qmrq8wFdStD56HQnSlkhrieZJYR/V2IOL5fGsNxCEl+cD/Wn4G5HjMdOwdxTmUEoHfp0jD9oRu0l3WywGVOBwgVSHI5pjBbZ/jgstu0gZF6M3QP8/ZvHM=
  - secure: VmjKYDAPWEvlGU7pm0XQg+ZM30kFb1NLOXtcEOTeGFxbxZuytBV3Ag2Ow6xA7KVVPt5T9+PtxNeCk+7cru3RwvxlrJhp27tbAI+mZ8t+tVf67Q38pHklvgL5K3O/tAZukxFh0EFFzjryDfl+H6tBw8nbW7tmGsJLPjXNuCymqq4=
  - secure: PI5tfIFW5GDbGMVh7qKv5cJ04nZ8lSbuHQ+yZUm13s15473CbnD94Tydvk1quOiy0w0SDoNepwvxPPnU1c3DGMRJ2Xs0LT7x2Nvj6Ss39c4kmixA7x3u8zZ6KbMbScsf9scffINTS+H+PB5Xid+b6o90g8SZ+xANpaPJ5J75ZFE=
  - secure: UGMnJ7EnlCFUqqZCZ/ysAror/DiHOsg0n/m0+xVmPxA4RY3LA7l7Ev3oFRk9NKKObkskd7wazWP6gjF6DnPDAyI6w5mw946EYddSJjuOI6mUG+EmQzh0arQw6OOF7BiJrVg5ee2jLLhfO66BhKF5/HWiI0iaNX/gK4SUzfGD3KA=
  - secure: dIRqbnAFC/GlAMsNSmD0GQY5Ofz4scExVcNCEkIa6k+p1IrS/yWZqon5TzchkpJNogx16cP9Y/8pNCGtwtIc8C4MIeiT1ahSBrxfQwfO3S4OtR2lmmY7wF56tShP/aPNsKFCkvMyKbnE2EgaoubBlnhRrKbwKS7cOzxl2YMRVB0=
  - secure: NBlncI7McMIAWFY0G273OhzF1wPb/nXlBfv6vjMVPIwrp3Nd2c3i8VEFvTkMhpC2uGO43te5HYeSK+V6Qk+NkuPwuPltDZwMU3Y6VCJkaWuCLntwQvIgQyHobajpKFRoioANWu0JJB14BvKc3Eale0hYLyUnQJVmmn6rM72j6o0=
  - secure: QzhNTewcZ4aV4iCANM1Jul/dnkih3vZhEs222uh1W6NLl+kLSIG/6vDnTPSqY/0GLvN3qclfHfyhmDsvDRqaw05GiOXiGFInPZmu4DgwuYBHn3racRl5c10Gf6/MnoHrzMxKP9oZ3vx5ZIXuM3TQ8Zfp8YovO2lRD07zfeW0bWI=
  - secure: Zo9EHPEY/e9CsWNppbuXYJ/NvXm7tlULuUU4SxZifklK3emslhKAosBxkFRJRbv+j1QeupWwkq+eHr1f99sC7a8yVP0dsL8wtfcFZvTPUt4xJ4ZpZaYeD/FZRKNlFXV51uCXnOX5Y6iDsLYDoNw64jpNaaEjoVK+H881OJ/K0zs=
  - secure: R/p2C68Vv6v6y2QXwfcrLfOIaT5lNl4JkTWLTAXzkb9ycBRtKOdI44NFuy37CJmboY4H1AjyeOrWrDrt6Dj8jbWcYZQLvHC/YCuraRBmdUPhC4OhGUa7KxRu3xb56G1NEbH8sWKO9zICD+KdhRTtAILLy1pURFIafYuEHCpoJMc=
  - secure: TUzgLSO60xqGYdnQLvSlmwIxfQSP7ULKmJePfM1AgjILv/e3dQz9UOyOPKKuWviRpacdhHaMxOvlcNdAQ7PvLPOtMTyUFUj58sS6UnIBA9rcNvhIY/5IzE3Y8GZb5lkiMaI25Ttet8xFaUsTFpnSBoEjHG5/bWZSlgzapmW3wVA=
  - secure: KVT87C0EASo0oTZVtLnk88gfGTQNwqkeJ3f4//hLTJVLvH/1kx1YjwWXTia8UNsTGeaGNBlaWhW8ecq/ApvlMrLd/u9L1F1XClEOPrl0USl3Vkd6sw2kk7CqDMKxVLwQgy21lEYbK83mv++ShjDVBjKCLPcyX4bJ979R/kuqxS0=
  - secure: jqZvooa5gqkck/mkh0MyC4hshvKjlGfsSBxA1iouX8XvDmc7W+1czdLQe+/BfH+gsUdHZ0Ja/zH01J+lDIHjG2tkJXGrjaFwweWu8CWIHYEivXfWiub+GYinLnwYj3hggiUZw+DcJBUqiIoOmcqQkkws+zxIRDEYmb9qfKcuIw4=
  - secure: WO+uUB0sbsATfcaMKvwdzm9az4kmlyG5wsk1x1KUssviIEQPxyUtJDxnGVhKf6vsU9caOdBdgdlDlifIbo+rs5KmNmc1ejWN8x5WhIN2OesqXpMbpQHT+mFCVmlGjNP9kX2YU1SqzWz1mNriYDDL3pmyBzhv9vBQiHtRHR3CdwE=
  - secure: XUmxYt8JEdS7rxEZhsAN2IL7lghe4hWXvWVinn1l+y5gKAvAKmIBRGC46NN29/OUAw1M5k6zhPvbcXRwz/yxMRKlJVgoSJFmZPL+pWcWVGTA96XX6xjrooCfKXAcSYzCp6R9rkOqhDdw+P/oiwNOEIkvgMpAmmetZJFxEEqK3nk=
  - secure: kC20Osz7q03ixCSa+dBeFwBmwm/VM3Gx1otfLUvU4paXVtkiXcu25C1YhqmBieH+nCg+1U4vrf+7oLOe/xOecnLV1qwNmR0iUcGjDBwcrvWd7X7D2tWcXzX9O6/D4/BGPrZpHK7oE2wKf2vjdTSGFP00iZrzW0JJS6RUPWkFVyg=
  - secure: hx3ZovC6Ehrqd4BY7FSWKdDXTIE6+J2Xypy+qznnwMFuE/y2RkqB05UUZUXrx0pNSxwQ2UwpXYF1eJkXDKQUtJb3cVa3a6AElbyjun+1P8vXsxVISIY/M1OxbHcVXlZXv+zObOwG57vN2MqmIDv2wF9/DCqlnIle8pPXCKPXahU=
  - secure: NZqJ7GnZrCxx+A+6gA3kecimugJtj67ZNw6T6+OXGEleRNQThzx4wG/dUkaxT6hnTb4s8MvltpqcilYrD8HjY4H1F15LPXDTwOlRLYwmTU0Ltp/5OhwXDqnOkoeSLzxwxGXTyFxE57M5etwwva43ctjzj0K2e6xQWKExkIrXrvM=
  - secure: Ns2Prog/2pUuSIG2m+DMcGd+aONuypYRX6se/H259O5VMQhuLcTsJLzj4Mke2zp7g60weUkMfSV+NZO88AhlYKxRLiDya+6VdpTML+IvswdMQd0/PAL3TQcQz/x5bf4HvdJgSCEC1xg5Thsory7Fn0gWW/Ci6goI2lsl3lkY4d4=
  - secure: E1oTarVGrO5ydc6+AXsnXZ3Sr0UPRUfvpxvkROh2BsZg+2jUCZqak3M82QknX/IXKcTCDx6zPiPF4G/LIvGQnGNGRendCXbGuMGEFb5xjKvcybjshFfRz4e6iZy8e5k9QVSbw4yLWozT3OYKH+fhYgW8mVEJuaz5wokIVy9SNZE=
  - secure: LBwUMVegpO51/honVoDtBe3IADZ12RPibSNotnDdCkzWQiJqJ4BY0PHLU5+sFQsAJtWcMeq/yXbDTc5RF5Tmt5+zSgFSn82CTpoJs2/0xDvIGV+B2FmnqwZe2xLbCNauCoeOUtiwDjseRfst8KAJIWYo++++DbfnJL5tasAv0zM=
  - secure: Gkxw6E08uMSmLTG60oKWe4+0z1V0fKMd0XbD5p3TaNo7ZK+MHyAKQOEwPO8Vw/FzqaaXL2z6MRU/grA6Zp5LBirFYUsQEhXJ2DtK8zzuKCZj0Bxswz7T3HKmmS0228pd74txIh6TU4QOaBkkzJ0u6yWfg/Hm0K0TrRSprQMf+EY=
  - secure: X4nyaCCRDb5scO2Cuc5FBxgLgG/ToCa06vC7H8XVDxpJ212aAEQNWJmrV4YHIs96k9mU/vQGgqXtVUq6Pz6JoVcY55oMyW/987qQuvIQF1apqwAQ4gFWSFXcbilAYZ3kAbRMKXS9ggx3W5+FqFjNExeK9NU/BN9pWGFS7Y6Yf80=
  - secure: i093wtsoCq0LhTw3WxxdH3R07ustObc9Fz1Nstaxi9WuLdlfoNN/OFK9GqfphmTaHpaSPTNiqQ64rBgXSqzoHi+SXwaSog5fVFQLFKQ1WsZ3FJTMUTqzPCBq+gvNfYJatov262K6zENFiTR6wbYxnNc7vJLNL49Bc2qLVEJP000=
  - secure: LS25ut+8NhQZCak9E5iAR2Ad8KMLFbRPHRnS8xlkuF/5HVr++fm712uP/g68is0kRzcBHPIO+1DskLSaiEcTpAhPEUKzxD8NuA6DTLKruwl8zmwF9jJa1KW2zh2ibBkDuiopueGWglGRicvJTwp9Wl1QapVWdl/SSfiM106aKL0=
  - secure: Ukjyn6YWg0JQdx69Cg4pPAkaM51htfLAVdsejPp9EwPcSI+OqeCDDk6ae+gSEFj0MqqIq+TlnzGVclJ+lU5tteV0B1N1B9Kn9NzcUUyQ6Xo/Fnx/2XP12cZAIHkNuaauoyFCPtz1b3hHQ67nSS2kZWtR2e0kEhN3bPfGHqOUMBc=
  - secure: fU04PzfD75kIptXaBCK5kCtki1tjnwehVIP4Sf+Y3eab3TPJb9tEJQ0wmJYiRi63bzjFSdBURoBZJXwzeelEZDCpO+c+HleGr6beG5b01eGLi8WdpSdvA66akR21fcobFbjWij/ecndqhzv12i9FvVo4cgmm1+P3MEmC+NATtqA=
  - secure: UWUH/u8RQ7sRkozei51GENDQh1760dsBhvlchDgksWSGdkfnE6FSsJJcXMHmXn/kNl90EItuNvVJVZE95QrQZ5DWDEwedFqFNJCuvUQ9OZN9S5LUQ0ODw9ZsgHecXDv9ysIpQD1Mt0mybh4t0c0n2Bkpy3AqbAIcSlbVZCLdGd4=
  - secure: ktI20Fd8kgNPn0LoWZ7K69ESq8QTg/k/BcRTuP9zq3aXbYUl3x3gITkHC3dY7/5+GLDK9eqxuCWkS+DNJ0kI4Gaf2FUJnOjs9IuNC/zM3ebYP6Q3/g5+Ij8V6iPIMVZRJrFwlMmr19PtHbVb5iSE0myurgl6PKY86pvTaP0YrYY=
  - secure: ihUP/CP9GlKLJ/CEdX7w64eFH2zLvLpUpbiE77h3A44qy+A2vaj8q6b87VwZoyMir6uLYu5C1UUO9KfdGgS8/Yj5SM0WqFnzKOER1F2rZuU2tstaK9mJ6n5TjsZ50mihrtJq4KBUPljH0G8yiHdfLqSt1yf9V5JwyXBIW8bmq98=
